[2023-05-10T00:00:02.967+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10T00:00:02.973+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-09T00:00:00+00:00 [queued]>
[2023-05-10T00:00:02.973+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T00:00:02.974+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-10T00:00:02.974+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T00:00:02.983+0000] {taskinstance.py:1309} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-05-09 00:00:00+00:00
[2023-05-10T00:00:02.987+0000] {standard_task_runner.py:55} INFO - Started process 70881 to run task
[2023-05-10T00:00:02.990+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-05-09T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpd2diy13t']
[2023-05-10T00:00:02.990+0000] {standard_task_runner.py:83} INFO - Job 399: Subtask is_api_available
[2023-05-10T00:00:03.036+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-05-09T00:00:00+00:00 [running]> on host 1f05588790e0
[2023-05-10T00:00:03.086+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-09T00:00:00+00:00
[2023-05-10T00:00:03.089+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:00:03.094+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:00:04.180+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:00:04.180+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:01:04.241+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:01:04.246+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:01:04.728+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:01:04.729+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:02:04.785+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:02:04.790+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:02:05.307+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:02:05.308+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:03:05.369+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:03:05.374+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:03:05.875+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:03:05.875+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:04:05.937+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:04:05.942+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:04:06.453+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:04:06.453+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:05:06.506+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:05:06.511+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:05:07.045+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:05:07.045+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:06:07.101+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:06:07.112+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:06:07.610+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:06:07.610+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:07:07.673+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:07:07.677+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:07:08.175+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:07:08.176+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:08:08.237+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:08:08.242+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:08:08.742+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:08:08.742+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:09:08.801+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:09:08.824+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:09:09.351+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:09:09.351+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:10:09.411+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:10:09.416+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:10:09.926+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:10:09.926+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:11:09.987+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:11:09.993+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:11:10.539+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:11:10.539+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:12:10.594+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:12:10.599+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:12:11.224+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:12:11.224+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:13:11.286+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:13:11.290+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:13:11.736+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:13:11.736+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:14:11.796+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:14:11.801+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:14:12.275+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:14:12.275+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:15:12.337+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:15:12.341+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:15:13.893+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:15:13.893+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:16:13.936+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:16:13.941+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:16:14.491+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:16:14.491+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:17:14.551+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:17:14.556+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:17:15.026+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:17:15.026+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:18:15.088+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:18:15.093+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:18:15.586+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:18:15.586+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:19:15.645+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:19:15.651+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:19:16.174+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:19:16.174+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:20:16.229+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:20:16.234+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:20:16.729+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:20:16.729+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:21:16.790+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:21:16.795+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:21:17.281+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:21:17.282+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:22:17.316+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:22:17.321+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:22:17.905+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:22:17.905+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:23:17.967+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:23:17.972+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:23:18.514+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:23:18.515+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:24:18.571+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:24:18.576+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:24:19.033+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:24:19.033+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:25:19.095+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:25:19.100+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:25:20.345+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:25:20.346+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:26:20.389+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:26:20.394+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:26:20.834+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:26:20.834+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:27:20.893+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:27:20.897+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:27:21.336+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:27:21.337+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:28:21.397+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:28:21.402+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:28:21.880+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-10T00:28:21.880+0000] {http.py:171} ERROR - Not Found
[2023-05-10T00:29:21.941+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-10T00:29:21.946+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-10T00:29:22.427+0000] {http.py:170} ERROR - HTTP error: 
[2023-05-10T00:29:22.427+0000] {http.py:171} ERROR - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>randomuser.me | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="inline-block">Web server is returning an unknown error</span>
              <span class="code-label">Error code 520</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=randomuser.me" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2023-05-10 00:29:22 UTC</div>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=randomuser.me" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Mumbai</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=randomuser.me" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">randomuser.me</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">7c4e11450a2e6efa</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">121.244.55.198</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=randomuser.me" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>


[2023-05-10T00:29:22.435+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 168, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 520 Server Error:  for url: https://randomuser.me/https://randomuser.me/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 137, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 128, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 158, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 211, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 172, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 520:
[2023-05-10T00:29:22.438+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=user_processing, task_id=is_api_available, execution_date=20230509T000000, start_date=20230510T000002, end_date=20230510T002922
[2023-05-10T00:29:22.447+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 399 for task is_api_available (520:; 70881)
[2023-05-10T00:29:22.484+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-10T00:29:22.507+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
