[2023-04-04T10:21:06.231+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2023-04-04T10:21:04.439343+00:00 [queued]>
[2023-04-04T10:21:06.237+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2023-04-04T10:21:04.439343+00:00 [queued]>
[2023-04-04T10:21:06.238+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T10:21:06.238+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-04T10:21:06.238+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T10:21:06.249+0000] {taskinstance.py:1309} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-04 10:21:04.439343+00:00
[2023-04-04T10:21:06.253+0000] {standard_task_runner.py:55} INFO - Started process 96159 to run task
[2023-04-04T10:21:06.255+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-04-04T10:21:04.439343+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9f30hjj3']
[2023-04-04T10:21:06.256+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask is_api_available
[2023-04-04T10:21:06.300+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-04-04T10:21:04.439343+00:00 [running]> on host 1f05588790e0
[2023-04-04T10:21:06.350+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T10:21:04.439343+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T10:21:04.439343+00:00
[2023-04-04T10:21:06.353+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:21:06.359+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:21:06.961+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:21:06.961+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:22:07.022+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:22:07.028+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:22:07.527+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:22:07.527+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:23:07.583+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:23:07.588+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:23:08.163+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:23:08.163+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:24:08.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:24:08.227+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:24:08.874+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:24:08.875+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:25:08.914+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:25:08.919+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:25:09.364+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:25:09.364+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:26:09.424+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:26:09.430+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:26:09.907+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:26:09.907+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:27:09.964+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:27:09.969+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:27:10.474+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:27:10.474+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:28:10.534+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-04-04T10:28:10.540+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-04-04T10:28:10.992+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-04-04T10:28:10.992+0000] {http.py:171} ERROR - Not Found
[2023-04-04T10:29:05.080+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-04-04T10:29:05.082+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 96159. PIDs of all processes in the group: [96159]
[2023-04-04T10:29:05.082+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 96159
[2023-04-04T10:29:05.082+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-04T10:29:05.134+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=96159, status='terminated', exitcode=0, started='10:21:05') (96159) terminated with exit code 0
