[2023-05-08T07:21:00.204+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-06T00:00:00+00:00 [queued]>
[2023-05-08T07:21:00.212+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-06T00:00:00+00:00 [queued]>
[2023-05-08T07:21:00.212+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-08T07:21:00.213+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-08T07:21:00.213+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-08T07:21:00.223+0000] {taskinstance.py:1309} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-05-06 00:00:00+00:00
[2023-05-08T07:21:00.227+0000] {standard_task_runner.py:55} INFO - Started process 105 to run task
[2023-05-08T07:21:00.229+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-05-06T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprje305tb']
[2023-05-08T07:21:00.229+0000] {standard_task_runner.py:83} INFO - Job 377: Subtask is_api_available
[2023-05-08T07:21:00.280+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-05-06T00:00:00+00:00 [running]> on host 1f05588790e0
[2023-05-08T07:21:00.332+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-05-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-06T00:00:00+00:00
[2023-05-08T07:21:00.335+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:21:00.341+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:21:01.230+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:21:01.230+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:22:01.270+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:22:01.274+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:22:01.769+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:22:01.769+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:23:01.820+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:23:01.826+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:23:02.301+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:23:02.301+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:24:02.342+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:24:02.347+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:24:02.829+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:24:02.830+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:25:02.891+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:25:02.896+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:25:03.404+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:25:03.404+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:26:03.466+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:26:03.471+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:26:03.945+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:26:03.945+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:27:03.995+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:27:04.000+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:27:04.492+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:27:04.492+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:28:04.550+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:28:04.555+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:28:05.057+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:28:05.058+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:29:05.119+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:29:05.124+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:29:05.619+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:29:05.619+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:30:05.680+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:30:05.685+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:30:06.171+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:30:06.171+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:31:06.230+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:31:06.235+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:31:06.720+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:31:06.721+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:32:06.782+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:32:06.787+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:32:07.269+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:32:07.270+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:33:07.330+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:33:07.334+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:33:07.820+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:33:07.820+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:34:07.878+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:34:07.883+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:34:08.352+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:34:08.352+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:35:08.411+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:35:08.416+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:35:08.892+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:35:08.892+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:36:08.946+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:36:08.950+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:36:09.426+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:36:09.426+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:37:09.470+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:37:09.475+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:37:09.966+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:37:09.966+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:38:10.026+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:38:10.030+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:38:10.539+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:38:10.539+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:39:10.559+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:39:10.564+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:39:11.041+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:39:11.041+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:40:11.102+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:40:11.107+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:40:11.584+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:40:11.584+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:41:11.646+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:41:11.650+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:41:12.135+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:41:12.135+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:42:12.194+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:42:12.199+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:42:12.674+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:42:12.675+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:43:12.734+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:43:12.738+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:43:13.219+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:43:13.219+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:44:13.281+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:44:13.285+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:44:13.780+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:44:13.781+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:45:13.797+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:45:13.803+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:45:14.312+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:45:14.312+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:46:14.374+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:46:14.377+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:46:14.872+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:46:14.872+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:47:14.902+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:47:14.906+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:47:15.443+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:47:15.443+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:48:15.505+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:48:15.510+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:48:15.979+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:48:15.979+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:49:16.034+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:49:16.039+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:49:16.513+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:49:16.513+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:50:16.530+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:50:16.534+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:50:17.325+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:50:17.325+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:51:17.372+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:51:17.377+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:51:17.860+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:51:17.860+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:52:17.920+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:52:17.924+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:52:18.401+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:52:18.401+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:53:18.462+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:53:18.466+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:53:18.963+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:53:18.963+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:54:19.022+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:54:19.027+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:54:19.517+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:54:19.518+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:55:19.534+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:55:19.539+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:55:20.016+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:55:20.016+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:56:20.074+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:56:20.078+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:56:20.572+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:56:20.572+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:57:20.607+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:57:20.611+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:57:21.103+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:57:21.103+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:58:21.147+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:58:21.152+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:58:21.646+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:58:21.646+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:59:21.678+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:59:21.682+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:59:22.173+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:59:22.173+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:00:22.234+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:00:22.239+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:00:22.723+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:00:22.723+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:01:22.782+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:01:22.786+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:01:23.266+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:01:23.266+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:02:23.326+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:02:23.330+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:02:23.856+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:02:23.856+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:03:23.880+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:03:23.885+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:03:24.405+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:03:24.405+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:04:24.466+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:04:24.471+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:04:24.951+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:04:24.951+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:05:25.010+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:05:25.014+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:05:25.531+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:05:25.531+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:06:25.590+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:06:25.595+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:06:26.073+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:06:26.073+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:07:26.134+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:07:26.139+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:07:26.615+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:07:26.615+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:08:26.674+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:08:26.679+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:08:27.185+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:08:27.186+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:09:27.239+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:09:27.243+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:09:27.716+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:09:27.716+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:10:27.770+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:10:27.775+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:10:28.262+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:10:28.263+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:11:28.323+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:11:28.327+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:11:28.811+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:11:28.811+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:12:28.870+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:12:28.875+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:12:29.342+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:12:29.342+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:13:29.402+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:13:29.406+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:13:29.883+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:13:29.884+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:14:29.943+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:14:29.948+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:14:30.430+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:14:30.430+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:15:30.490+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:15:30.494+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:15:30.972+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:15:30.972+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:16:31.022+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:16:31.028+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:16:31.527+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:16:31.527+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:17:31.589+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:17:31.594+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:17:32.066+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:17:32.066+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:18:32.074+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:18:32.080+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:18:32.560+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:18:32.560+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:19:32.622+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:19:32.627+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:19:33.126+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:19:33.127+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:20:33.158+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:20:33.163+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:20:33.633+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:20:33.633+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:21:33.694+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:21:33.698+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:21:34.246+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:21:34.246+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:22:34.306+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:22:34.311+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:22:34.781+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:22:34.781+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:23:34.843+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:23:34.847+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:23:35.346+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:23:35.347+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:24:35.395+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:24:35.400+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:24:35.892+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:24:35.892+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:25:35.954+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:25:35.959+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:25:36.445+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:25:36.445+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:26:36.506+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:26:36.510+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:26:36.997+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:26:36.997+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:27:37.058+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:27:37.065+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:27:37.537+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:27:37.537+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:28:37.598+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:28:37.604+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:28:38.088+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:28:38.088+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:29:38.110+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:29:38.115+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:29:38.605+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:29:38.605+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:30:38.666+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:30:38.671+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:30:39.152+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:30:39.152+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:31:39.214+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:31:39.219+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:31:39.713+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:31:39.713+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:32:39.774+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:32:39.779+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:32:40.366+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:32:40.366+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:33:40.385+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:33:40.390+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:33:40.869+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:33:40.869+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:34:40.930+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:34:40.934+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:34:41.437+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:34:41.437+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:35:41.461+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:35:41.467+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:35:41.964+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:35:41.965+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:36:42.021+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:36:42.026+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:36:42.529+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:36:42.530+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:37:42.590+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:37:42.595+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:37:43.442+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:37:43.442+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:38:43.463+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:38:43.468+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:38:43.994+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:38:43.995+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:39:44.054+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:39:44.059+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:39:44.624+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:39:44.624+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:40:44.686+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:40:44.692+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:40:45.193+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:40:45.193+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:41:45.254+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:41:45.259+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:41:45.754+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:41:45.754+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:42:45.816+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:42:45.821+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:42:46.404+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:42:46.405+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:43:46.466+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:43:46.473+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:43:46.974+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:43:46.974+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:44:47.034+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:44:47.039+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:44:47.543+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:44:47.543+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:45:47.589+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:45:47.594+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:45:48.087+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:45:48.087+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:46:48.148+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:46:48.153+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:46:48.646+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:46:48.647+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:47:48.706+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:47:48.711+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:47:49.194+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:47:49.194+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:48:49.245+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:48:49.251+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:48:49.740+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:48:49.741+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:49:49.746+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:49:49.752+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:49:50.233+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:49:50.234+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:50:50.295+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:50:50.301+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:50:50.776+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:50:50.777+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:51:50.838+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:51:50.842+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:51:51.335+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:51:51.335+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:52:51.396+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:52:51.402+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:52:51.885+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:52:51.885+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:53:51.947+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:53:51.953+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:53:52.435+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:53:52.435+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:54:52.488+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:54:52.494+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:54:53.757+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:54:53.757+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:55:53.818+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:55:53.823+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:55:54.327+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:55:54.327+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:56:54.386+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:56:54.392+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:56:54.873+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:56:54.873+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:57:54.934+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:57:54.939+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:57:55.426+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:57:55.426+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:58:55.486+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:58:55.491+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:58:56.027+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:58:56.027+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:59:56.088+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:59:56.093+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:59:56.594+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:59:56.594+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:00:56.654+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:00:56.659+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:00:57.163+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:00:57.164+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:01:57.203+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:01:57.208+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:01:57.807+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:01:57.807+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:02:57.868+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:02:57.873+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:02:58.374+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:02:58.374+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:03:58.434+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:03:58.439+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:03:58.998+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:03:58.998+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:04:59.058+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:04:59.063+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:04:59.669+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:04:59.670+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:05:59.730+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:05:59.745+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:06:00.234+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:06:00.234+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:07:00.290+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:07:00.296+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:07:00.804+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:07:00.804+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:08:00.839+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:08:00.844+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:08:01.379+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:08:01.379+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:09:01.428+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:09:01.433+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:09:02.011+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:09:02.011+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:10:02.073+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:10:02.078+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:10:02.586+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:10:02.587+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:11:02.648+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:11:02.654+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:11:03.380+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:11:03.380+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:12:03.442+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:12:03.447+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:12:03.969+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:12:03.969+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:13:04.030+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:13:04.035+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:13:04.558+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:13:04.558+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:14:04.563+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:14:04.569+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:14:05.062+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:14:05.062+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:15:05.122+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:15:05.127+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:15:05.698+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:15:05.699+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:16:05.758+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:16:05.763+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:16:06.719+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:16:06.720+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:17:06.778+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:17:06.784+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:17:07.272+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:17:07.272+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:18:07.334+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:18:07.339+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:18:07.812+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:18:07.812+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:19:07.872+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:19:07.878+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:19:08.366+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:19:08.367+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:20:08.398+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:20:08.403+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:20:08.881+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:20:08.882+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:21:08.938+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:21:08.942+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:21:09.468+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:21:09.468+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:22:09.512+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:22:09.517+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:22:10.015+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:22:10.015+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:23:10.074+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:23:10.078+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:23:10.555+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:23:10.555+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:24:10.557+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:24:10.563+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:24:11.161+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:24:11.162+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:25:11.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:25:11.227+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:25:11.742+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:25:11.742+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:26:11.802+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:26:11.807+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:26:12.284+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:26:12.285+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:27:12.346+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:27:12.352+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:27:12.828+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:27:12.828+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:28:12.880+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:28:12.885+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:28:13.370+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:28:13.370+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:29:13.430+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:29:13.434+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:29:13.926+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:29:13.927+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:30:13.984+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:30:13.989+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:30:14.461+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:30:14.462+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:31:14.518+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:31:14.523+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:31:15.007+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:31:15.007+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:32:15.066+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:32:15.071+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:32:15.555+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:32:15.555+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:33:15.616+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:33:15.620+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:33:16.092+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:33:16.092+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:34:16.154+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:34:16.159+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:34:16.627+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:34:16.627+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:35:16.666+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:35:16.671+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:35:17.137+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:35:17.138+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:36:17.198+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:36:17.203+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:36:17.720+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:36:17.720+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:37:17.778+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:37:17.782+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:37:18.296+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:37:18.297+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:38:18.358+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:38:18.363+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:38:18.843+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:38:18.843+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:39:18.902+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:39:18.908+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:39:19.396+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:39:19.396+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:40:19.454+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:40:19.461+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:40:19.947+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:40:19.947+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:41:20.001+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:41:20.006+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:41:20.478+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:41:20.479+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:42:20.538+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:42:20.542+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:42:21.009+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:42:21.010+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:43:21.070+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:43:21.076+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:43:21.559+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:43:21.559+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:44:21.618+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:44:21.623+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:44:22.112+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:44:22.113+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:45:22.174+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:45:22.179+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:45:22.652+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:45:22.652+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:46:22.706+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:46:22.710+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:46:23.204+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:46:23.204+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:47:23.262+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:47:23.267+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:47:23.760+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:47:23.760+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:48:23.822+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:48:23.827+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:48:24.331+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:48:24.331+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:49:24.390+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:49:24.394+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:49:24.893+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:49:24.893+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:50:24.950+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:50:24.955+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:50:25.428+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:50:25.428+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:51:25.474+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:51:25.479+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:51:25.969+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:51:25.969+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:52:26.030+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:52:26.046+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:52:26.551+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:52:26.551+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:53:26.613+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:53:26.619+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:53:27.094+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:53:27.095+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:54:27.135+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:54:27.141+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:54:27.629+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:54:27.630+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:54:55.573+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-05-08T09:55:00.716+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
