[2023-05-08T07:21:00.221+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2023-05-08T07:21:00.227+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2023-05-08T07:21:00.227+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-08T07:21:00.227+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-08T07:21:00.227+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-08T07:21:00.238+0000] {taskinstance.py:1309} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-05-07 00:00:00+00:00
[2023-05-08T07:21:00.243+0000] {standard_task_runner.py:55} INFO - Started process 106 to run task
[2023-05-08T07:21:00.245+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-05-07T00:00:00+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfud045wu']
[2023-05-08T07:21:00.245+0000] {standard_task_runner.py:83} INFO - Job 378: Subtask is_api_available
[2023-05-08T07:21:00.294+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-05-07T00:00:00+00:00 [running]> on host 1f05588790e0
[2023-05-08T07:21:00.350+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-07T00:00:00+00:00
[2023-05-08T07:21:00.353+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:21:00.359+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:21:01.008+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:21:01.008+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:22:01.070+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:22:01.076+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:22:01.642+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:22:01.642+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:23:01.696+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:23:01.701+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:23:02.208+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:23:02.208+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:24:02.264+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:24:02.270+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:24:02.765+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:24:02.765+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:25:02.826+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:25:02.832+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:25:03.326+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:25:03.326+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:26:03.366+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:26:03.370+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:26:03.864+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:26:03.864+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:27:03.926+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:27:03.930+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:27:04.433+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:27:04.433+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:28:04.495+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:28:04.501+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:28:04.990+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:28:04.990+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:29:05.052+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:29:05.059+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:29:05.548+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:29:05.548+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:30:05.583+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:30:05.589+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:30:06.080+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:30:06.080+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:31:06.106+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:31:06.110+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:31:06.616+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:31:06.616+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:32:06.674+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:32:06.679+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:32:07.161+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:32:07.161+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:33:07.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:33:07.227+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:33:07.717+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:33:07.717+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:34:07.778+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:34:07.782+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:34:08.295+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:34:08.295+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:35:08.357+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:35:08.361+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:35:08.846+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:35:08.847+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:36:08.906+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:36:08.910+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:36:09.391+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:36:09.391+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:37:09.450+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:37:09.454+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:37:09.938+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:37:09.938+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:38:09.998+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:38:10.003+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:38:10.491+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:38:10.491+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:39:10.496+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:39:10.501+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:39:10.980+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:39:10.980+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:40:11.041+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:40:11.047+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:40:11.547+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:40:11.548+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:41:11.606+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:41:11.610+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:41:12.127+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:41:12.127+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:42:12.185+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:42:12.191+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:42:12.690+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:42:12.691+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:43:12.727+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:43:12.732+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:43:13.209+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:43:13.209+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:44:13.249+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:44:13.254+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:44:13.751+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:44:13.751+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:45:13.813+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:45:13.818+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:45:14.312+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:45:14.313+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:46:14.374+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:46:14.378+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:46:14.878+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:46:14.878+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:47:14.939+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:47:14.944+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:47:15.471+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:47:15.471+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:48:15.530+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:48:15.535+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:48:16.007+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:48:16.007+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:49:16.066+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:49:16.070+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:49:16.563+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:49:16.563+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:50:16.626+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:50:16.630+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:50:17.312+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:50:17.312+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:51:17.358+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:51:17.363+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:51:17.881+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:51:17.881+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:52:17.910+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:52:17.915+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:52:18.387+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:52:18.387+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:53:18.446+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:53:18.451+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:53:18.927+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:53:18.927+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:54:18.986+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:54:18.991+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:54:19.485+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:54:19.485+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:55:19.530+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:55:19.535+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:55:20.010+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:55:20.011+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:56:20.070+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:56:20.074+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:56:20.573+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:56:20.573+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:57:20.634+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:57:20.638+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:57:21.111+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:57:21.112+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:58:21.170+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:58:21.174+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:58:21.642+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:58:21.642+0000] {http.py:171} ERROR - Not Found
[2023-05-08T07:59:21.702+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T07:59:21.706+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T07:59:22.185+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T07:59:22.186+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:00:22.246+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:00:22.250+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:00:22.735+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:00:22.735+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:01:22.794+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:01:22.798+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:01:23.282+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:01:23.282+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:02:23.342+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:02:23.347+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:02:23.854+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:02:23.854+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:03:23.898+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:03:23.902+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:03:24.382+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:03:24.383+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:04:24.432+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:04:24.438+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:04:24.939+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:04:24.939+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:05:24.998+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:05:25.003+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:05:25.490+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:05:25.490+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:06:25.550+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:06:25.555+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:06:26.046+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:06:26.047+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:07:26.049+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:07:26.054+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:07:26.548+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:07:26.548+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:08:26.609+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:08:26.615+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:08:27.091+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:08:27.091+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:09:27.148+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:09:27.153+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:09:27.626+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:09:27.626+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:10:27.685+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:10:27.690+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:10:28.172+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:10:28.172+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:11:28.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:11:28.227+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:11:28.721+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:11:28.721+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:12:28.758+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:12:28.763+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:12:29.239+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:12:29.239+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:13:29.298+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:13:29.302+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:13:29.787+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:13:29.787+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:14:29.847+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:14:29.852+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:14:30.335+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:14:30.335+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:15:30.395+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:15:30.400+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:15:30.874+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:15:30.874+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:16:30.934+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:16:30.939+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:16:31.438+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:16:31.439+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:17:31.494+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:17:31.499+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:17:32.079+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:17:32.080+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:18:32.132+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:18:32.138+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:18:32.626+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:18:32.626+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:19:32.686+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:19:32.691+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:19:33.181+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:19:33.182+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:20:33.238+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:20:33.243+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:20:33.726+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:20:33.726+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:21:33.766+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:21:33.770+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:21:34.285+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:21:34.285+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:22:34.346+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:22:34.350+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:22:34.824+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:22:34.824+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:23:34.885+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:23:34.890+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:23:35.396+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:23:35.397+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:24:35.455+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:24:35.460+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:24:35.956+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:24:35.957+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:25:36.015+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:25:36.020+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:25:36.521+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:25:36.522+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:26:36.582+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:26:36.586+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:26:37.076+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:26:37.076+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:27:37.138+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:27:37.142+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:27:37.622+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:27:37.622+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:28:37.658+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:28:37.663+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:28:38.148+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:28:38.148+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:29:38.198+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:29:38.203+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:29:38.685+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:29:38.685+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:30:38.746+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:30:38.752+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:30:39.245+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:30:39.245+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:31:39.306+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:31:39.312+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:31:39.798+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:31:39.799+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:32:39.838+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:32:39.844+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:32:40.423+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:32:40.424+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:33:40.464+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:33:40.470+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:33:40.946+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:33:40.946+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:34:41.006+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:34:41.011+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:34:41.481+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:34:41.481+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:35:41.539+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:35:41.544+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:35:42.035+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:35:42.035+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:36:42.070+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:36:42.074+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:36:42.560+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:36:42.561+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:37:42.622+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:37:42.626+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:37:43.429+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:37:43.429+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:38:43.490+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:38:43.494+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:38:43.990+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:38:43.990+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:39:44.050+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:39:44.054+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:39:44.563+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:39:44.563+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:40:44.625+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:40:44.629+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:40:45.114+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:40:45.114+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:41:45.174+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:41:45.178+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:41:45.685+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:41:45.685+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:42:45.746+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:42:45.751+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:42:46.450+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:42:46.450+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:43:46.510+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:43:46.516+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:43:46.979+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:43:46.980+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:44:47.038+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:44:47.043+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:44:47.559+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:44:47.559+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:45:47.618+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:45:47.622+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:45:48.122+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:45:48.122+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:46:48.182+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:46:48.189+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:46:48.675+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:46:48.675+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:47:48.737+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:47:48.743+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:47:49.243+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:47:49.243+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:48:49.255+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:48:49.259+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:48:49.736+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:48:49.736+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:49:49.794+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:49:49.800+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:49:50.274+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:49:50.274+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:50:50.334+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:50:50.338+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:50:50.809+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:50:50.809+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:51:50.870+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:51:50.875+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:51:51.357+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:51:51.357+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:52:51.418+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:52:51.424+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:52:51.945+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:52:51.945+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:53:51.998+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:53:52.003+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:53:52.509+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:53:52.510+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:54:52.570+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:54:52.575+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:54:53.063+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:54:53.064+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:55:53.122+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:55:53.127+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:55:53.666+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:55:53.667+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:56:53.698+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:56:53.703+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:56:54.229+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:56:54.229+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:57:54.290+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:57:54.294+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:57:54.797+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:57:54.797+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:58:54.851+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:58:54.856+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:58:55.343+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:58:55.343+0000] {http.py:171} ERROR - Not Found
[2023-05-08T08:59:55.386+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T08:59:55.390+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T08:59:55.994+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T08:59:55.994+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:00:56.018+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:00:56.023+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:00:56.545+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:00:56.545+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:01:56.606+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:01:56.611+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:01:57.183+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:01:57.183+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:02:57.242+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:02:57.247+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:02:57.783+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:02:57.783+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:03:57.843+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:03:57.848+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:03:58.435+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:03:58.435+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:04:58.471+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:04:58.477+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:04:59.134+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:04:59.134+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:05:59.177+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:05:59.183+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:05:59.666+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:05:59.666+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:06:59.714+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:06:59.719+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:07:00.222+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:07:00.223+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:08:00.284+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:08:00.289+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:08:00.818+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:08:00.818+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:09:00.849+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:09:00.855+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:09:01.343+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:09:01.344+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:10:01.357+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:10:01.362+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:10:01.913+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:10:01.913+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:11:01.950+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:11:01.957+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:11:02.473+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:11:02.473+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:12:02.534+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:12:02.539+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:12:03.186+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:12:03.186+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:13:03.246+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:13:03.250+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:13:03.740+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:13:03.740+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:14:03.798+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:14:03.803+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:14:04.291+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:14:04.292+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:15:04.350+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:15:04.355+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:15:04.875+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:15:04.875+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:16:04.934+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:16:04.939+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:16:05.453+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:16:05.453+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:17:05.514+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:17:05.519+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:17:06.078+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:17:06.079+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:18:06.138+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:18:06.143+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:18:06.647+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:18:06.647+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:19:06.706+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:19:06.711+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:19:07.193+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:19:07.194+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:20:07.250+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:20:07.255+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:20:07.745+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:20:07.745+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:21:07.804+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:21:07.809+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:21:08.302+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:21:08.303+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:22:08.362+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:22:08.366+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:22:08.861+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:22:08.861+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:23:08.922+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:23:08.927+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:23:09.553+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:23:09.554+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:24:09.614+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:24:09.618+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:24:10.131+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:24:10.131+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:25:10.192+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:25:10.197+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:25:10.687+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:25:10.687+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:26:10.749+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:26:10.754+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:26:11.231+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:26:11.232+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:27:11.290+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:27:11.294+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:27:11.828+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:27:11.828+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:28:11.890+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:28:11.894+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:28:12.361+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:28:12.361+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:29:12.423+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:29:12.427+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:29:12.907+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:29:12.907+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:30:12.966+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:30:12.972+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:30:13.472+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:30:13.472+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:31:13.525+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:31:13.530+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:31:14.025+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:31:14.025+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:32:14.082+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:32:14.086+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:32:14.597+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:32:14.597+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:33:14.658+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:33:14.663+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:33:15.133+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:33:15.133+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:34:15.144+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:34:15.149+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:34:15.619+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:34:15.619+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:35:15.666+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:35:15.671+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:35:16.166+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:35:16.166+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:36:16.226+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:36:16.231+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:36:16.748+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:36:16.749+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:37:16.810+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:37:16.814+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:37:17.437+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:37:17.437+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:38:17.498+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:38:17.503+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:38:17.998+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:38:17.998+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:39:18.055+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:39:18.060+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:39:18.532+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:39:18.532+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:40:18.590+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:40:18.594+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:40:19.111+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:40:19.111+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:41:19.173+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:41:19.178+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:41:19.678+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:41:19.678+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:42:19.738+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:42:19.742+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:42:20.230+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:42:20.230+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:43:20.287+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:43:20.292+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:43:20.833+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:43:20.833+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:44:20.894+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:44:20.898+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:44:21.374+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:44:21.374+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:45:21.434+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:45:21.440+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:45:21.925+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:45:21.925+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:46:21.961+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:46:21.966+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:46:22.462+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:46:22.462+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:47:22.524+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:47:22.529+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:47:23.036+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:47:23.036+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:48:23.072+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:48:23.077+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:48:23.552+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:48:23.552+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:49:23.613+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:49:23.617+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:49:24.107+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:49:24.107+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:50:24.150+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:50:24.154+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:50:24.662+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:50:24.662+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:51:24.722+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:51:24.727+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:51:25.210+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:51:25.210+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:52:25.270+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:52:25.277+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:52:25.811+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:52:25.811+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:53:25.870+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:53:25.874+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:53:26.354+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:53:26.354+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:54:26.409+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-08T09:54:26.414+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-08T09:54:26.908+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-08T09:54:26.908+0000] {http.py:171} ERROR - Not Found
[2023-05-08T09:54:55.574+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-05-08T09:55:00.715+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
